### PR TITLE
Gb3200b

### PR DESCRIPTION
**Pull request by Korndaweizen**
Added support for Gb3200b as described in https://discourse.voss.earth/t/gd3200b-anzahl-angezeigter-ordner-erst-nach-2-tem-auflegen-der-karte-richtig/9732/28

### CODE REVIEW

**Comment by Korndaweizen** [comment]
@marco-117 sorry for the whitespace changes...

**Comment by Korndaweizen** [comment]
Need to verify and solve a potential issue with the 000.mp3 track included in the filecount. Trackcount should be n-1 instead of n, as n does not exist if a 000 file is present

**Comment by Korndaweizen** [comment]
Fixed and working :)

**Comment by Korndaweizen** [comment]
Note: This does not fix the issue with surplus track-finished events when an advert is done.

**Comment by Korndaweizen** [comment]
and now it does...

**Comment by marco-117** [comment]
Hi, there is a new and working player on the market. Morte Information are here: 
[https://discourse.voss.earth/t/neue-beute-der-leiterkartenpiraten-der-lkp-player/11631?u=marco-117](LKP-Player)

These new player out there are not stable at some points and i dont recommend these and also will not support these in my software. It takes to much effort and at the end they will not work properly. Please use the LKP Player or the original DF Player from DF Robot.

**Pull request closed without merging**
